name: Validate

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"
  # schedule:
  # - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  # We're not published on HACS (yet)
  # validate-hacs:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v5
  #   - name: HACS validation
  #     uses: hacs/action@main
  #     with:
  #       category: integration
  validate-hassfest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: home-assistant/actions/hassfest@master

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"
        cache-dependency-path: "requirements_test.txt"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_test.txt
    - name: Run pytest
      run: |
        pytest --cov=custom_components.50five --cov-report=term-missing --cov-report=xml tests/

  zip:
    name: Build ZIP
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Create ZIP
      shell: bash
      run: |
        cd "${{ github.workspace }}/custom_components/50five"
        zip ha-50five.zip -r ./
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ha-50five
        path: ${{ github.workspace }}/custom_components/50five/ha-50five.zip
        retention-days: 30
